spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/office?characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    cache: false
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
    timeout: 1000ms



######################### Druid连接池的配置信息  #################
spring.druid.initialSize: 5                                 #初始化连接大小
spring.druid.minIdle: 5                                     #最小连接池数量
spring.druid.maxActive: 20                                  #最大连接池数量
spring.druid.maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
spring.druid.timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.druid.minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
spring.druid.validationQuery: SELECT 1 FROM DUAL            #测试连接
spring.druid.testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
spring.druid.testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
spring.druid.testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
spring.druid.poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
spring.druid.maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
spring.druid.filters: stat,wall,log4j                       #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
spring.druid.connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;慢SQL记录
mybatis:
  mapper-locations:  classpath:mappers/*.xml
  type-aliases-package: com.office.pojo
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: /office




########################### redis #########################







